### ISSUE TITLE
Team page: useless filter

### ISSUE THREAD

**Issue by xmonader** [threefoldfoundation/www_threefold_io#343]
![image](https://github.com/threefoldfoundation/www_threefold_io/assets/64129/ae85af2e-5281-47d9-b867-651b69725a13)

this filter shows only "All" option

**Comment by Amrani-Farouk-Hossam-Eddine** [comment]
Hi, i want to take it if there is no one currently working on it just explaine me what you want in filter

**Comment by samtaggart** [comment]
> Hi, i want to take it if there is no one currently working on it just explaine me what you want in filter

Thanks @Amrani-Farouk-Hossam-Eddine for your offer! 🙏  I think in this instance we have it covered but I appreciate it.

**Comment by samtaggart** [comment]
I think we need to recategorize our people ...

So let's set some tasks:

- [ ] @ehab-hassan Look into why the filter is not working and fix
- [ ] @Karoline888 & Nayer look through team spreadsheet (sent to them) to confirm current team
- [ ] @amandacaster go through spreadsheet and see where people pages need to be created or removed (after Karoline / Nayer review)
- [ ] @amandacaster go through spreadsheet and see where we need to add or remove people from TG group
- [ ] @amandacaster Update existing people with correct tag – either threefold_tech, threefold_dmcc, or codescalers_egypt (remove all other tags – e.g. aci, wisdom_council)
- [ ] @amandacaster Remove any people pages which should no longer exist
- [ ] @samtaggart Add / remove people from internal Telegram group

**Comment by samtaggart** [comment]
Reviews have been done.

@amandacaster Please go through for each person that already has a people page and update their membership to either threefold_tech, threefold_dmcc, or codescalers_egypt. Please update every person's catefory to only foundation.

@amandacaster Since right now we are not using threefold_data, please reach out to each person who needs a page added and ask them for the required information for the people page along with a decent headshot.

**Comment by xmonader** [comment]
@samtaggart I'm not sure about these codescalers, dmcc, .. etc

This how things were, I don't believe it was company based and also it feels really strange if i go to a website and see the ppl behind it are in different companies
![image](https://github.com/threefoldfoundation/www_threefold_io/assets/64129/ef604bec-0e17-4eb8-ac2a-0e97a4635bc4)

**Comment by samtaggart** [comment]
> [@samtaggart](https://github.com/samtaggart) I'm not sure about these codescalers, dmcc, .. etc
> 
> This how things were, I don't believe it was company based and also it feels really strange if i go to a website and see the ppl behind it are in different companies ![image](https://private-user-images.githubusercontent.com/64129/310796015-ef604bec-0e17-4eb8-ac2a-0e97a4635bc4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxMzkzNDAsIm5iZiI6MTcxMDEzOTA0MCwicGF0aCI6Ii82NDEyOS8zMTA3OTYwMTUtZWY2MDRiZWMtMGUxNy00ZWI4LWFjMmEtMGU5N2E0NjM1YmM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDA2MzcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4MWNmNWQ0NTViYTIwNTk5NDk4NDIwN2M0ZGRkN2UzNDZiNDY5MDUxOWEyNjRjMmZjODJkYWE2M2JhMTgyM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1ODOtVLmoHv_JxUulV-7o547Ck5vSAGhtKv1m2r2Da0)

OK fair enough.

Maybe best for now just to put "team" for now.

What do you think @xmonader – as the idea is to add people from the community as well, then we can add in other tags like "farmer," "grid user," etc.

**Comment by samtaggart** [comment]
@amandacaster 

Tomorrow can you please update the following "people" pages on www_threefold_io, using the latest information from threefold_data

1. Ahmed Thabet
2. Omar Abdulaziz
3. Ahmed Hanafy

And add new pages for the following people on www_threefold_io using their info from threefold_data:

1. Alaa Elattar
2. Abdulraham Elawady
3. Eslam Nawara

This is as of right now, let's check tomorrow if there have been any new commits since Eslam's addition.

Then after you are done, @timurgordon will basically merge www_threefold_io people content into threefold_data and we will start pulling from threefold_data for the people page, so that when anyone updates their people page on threefold_data it will go directly to threefold.io people page.

Let me know if there are any questions / let's talk about it in the morning. Thank you!

**Comment by amandacaster** [comment]
@samtaggart I am done making the changes  for 

1. Ahmed Thabet
2. Omar Abdulaziz
3. Ahmed Hanafy
 
 and adding the new pages for 
 
1. Alaa Elattar
2. Abdulraham Elawady
3. Eslam Nawara

@Nayer-Sobhy, @xmonader please have a look and let me know if you and the team would like me to make any changes.

**Comment by samtaggart** [comment]
It looks good to me @amandacaster !

**Comment by samtaggart** [comment]
Now @timurgordon we need to move www_threefold_io people folder over to threefold_data person folder and start pulling from threefold_data person folder for the website.

**Comment by samtaggart** [comment]
@timurgordon Looks like there have been no pushes to threefold_data since my last comment.

So please make sure www_threefold_io people folder is moved over to threefold_data and that we can start pulling from there in case anyone updates their files moving forward.

**Comment by timurgordon** [comment]
> @timurgordon Looks like there have been no pushes to threefold_data since my last comment.
> 
> So please make sure www_threefold_io people folder is moved over to threefold_data and that we can start pulling from there in case anyone updates their files moving forward.

Progress is on the brach development_zola, adding scripts to add data from threefold_io and format accordingly. The people directory is in sync, working on blogs and news
