### ISSUE TITLE
blog is not news

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/www_threefold_io#357]
<img width="890" alt="image" src="https://github.com/threefoldfoundation/www_threefold_io/assets/6021844/9d38be9c-18e1-479a-ae21-29bc63824eeb">

why latest?

blogs should be stories and relevant info

**Comment by samtaggart** [comment]
OK for now I updated the text there (on development) and will need to do some reworking on blog content / moving some items to newsroom, etc

**Comment by marionrvrn** [comment]
**BLOG** 

- [ ] The "hero" section has to be modified to indicate that we are in BLOG - now we can't really tell the difference between the two pages 
- [ ] Move this blog [ThreeFold X H.E.R. DAO – Cultivating Digital Sovereignty and Inclusive Innovation in Dar Es Salaam ](https://www.threefold.io/blog/threefold-herdao-dar/) from blog to news and exchange instead of “Recap TF x H.E.R” - we also need to improve the content 
- [ ] [African Summit I](https://www.threefold.io/newsroom/africanregensummit/) and [II](https://www.threefold.io/newsroom/africa-regen-ii/) (it redirects to the forum post) are in News and [African Summit II](https://www.threefold.io/newsroom/africa-regen-ii/) which is a full recap is in Blog but also in Forum. The recap of Summit II should appear in the news and forum and be removed from the blog. As there is no African Summit I blog, we could use the existing blog African Summit II and write in a different way (maybe be a summary of the outcomes of the two events?) 
- [ ] “[Introducing Mycelium](https://www.threefold.io/blog/introducing-mycelium/)” blog has the same title and image as the “[Introducing Mycelium](https://www.threefold.io/newsroom/introducing-myceliium/)” news, so we have to modify one of them because it can be confusing + the blog has the complete content while the news is only a short summary and a redirection to a forum post that has the same content as the blog - see how can we improve both contents
- [ ] Change the images of the latest blogs (up to Mycelium) for more meaningful/inviting images

**NEWS**

- [ ] Same as blog --> The "hero" section has to be modified to indicate that we are in NEWS.
- [ ] Replace the headlines and images of some news stories with more inviting headlines “Dunia Yetu…”.
- [ ] This [Introducing Dunia Yetu](https://www.threefold.io/newsroom/dunia-yetu/) isn't really written as "news" and could be more inviting. It's linked to a forum post but should also be written as a blog
