### ISSUE TITLE
Add utilization stats to threefold.io

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_io#386]
Similar to how Akash does it here https://stats.akash.network/ we want to add just a few utilization stats to the website, as we currently have for capacity stats.

Potentially:

- TFT spent (last 30 days)
- TFT spent (total)
- Contracts deployed (last 30 days)
- Contracts deployed (total)

Then we need to decide how we want to show these stats (probably in a line graph like below).

![Screenshot 2024-03-01 at 09 40 55 (1)](https://github.com/threefoldfoundation/www_threefold_io/assets/50134479/c80ab500-f272-46ad-b5fd-0401d40f0cfb)

**Comment by samtaggart** [comment]
Comment from @scottyeager 

_Gathering these figures requires use of GraphQL, so that probably involves adding a bit of Javascript._

_There's some limitations too. Specially in regard to what was requested, deployment contracts only have a creation timestamp and a current state. There's no way to determine when a contract was deleted._

_That means creating a graph of newly created contracts is fairly straightforward, but graphing the active contract count is not._

Comment from me:

_I'm not saying those need to be the stats exactly it was just a proposition._

_I also think it's OK to talk about contracts created even if they are no longer active. It still shows utilization._

_If you have better recommendations for which stats to show please let me know!_

**Comment by Mik-TF** [comment]
Status? @scottyeager @samtaggart

**Comment by scottyeager** [comment]
I'm not aware of any progress on this. I will update my take though:

* The best approach would be to ask for whatever stats to be added to grid proxy, either as a new endpoint or added to an existing
* The most meaningful stats we have for utilization that are readily available are the current amount of each resource reserved (cpu, ram, ssd, hdd)
* Graphing anything over time is a gonna be a big project in itself
* Contracts are not really meaningful per se since there are empty contracts that don't reserve any resources and never get deleted (probably more of these all the time). We could ask for a filtered view of contracts that are active and have some resources reserved

**Comment by samtaggart** [comment]
Any idea the type of resources this would take? We can propose to Kristof and Thabet but maybe this needs to stay on the backburner for now?

**Comment by Mik-TF** [comment]
> The most meaningful stats we have for utilization that are readily available are the current amount of each resource reserved (cpu, ram, ssd, hdd)

I agree with this. We should focus on those numbers, if we want to put out there real-time numbers.

But as Sam said, we can put in back burner if we don't have resources for this.

**Comment by Mik-TF** [comment]
Ok good. Closing for now. We can see later if we have resources for this.
