### ISSUE TITLE
12.12 related updates

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_io#501]
Hi, several comments on the website:

- Menu should be Take Action, not Take Actions (yes you can take multiple actions but it sounds weird)
- Any button that says "Pre-register now" (appears on multiple pages) should instead be something like "Sign Up Today" or "Take the Next Step" ... or something similar (maybe ask around for the right wording). Since the form allows people to do different things – register interest, pre-order, or order.
- On the action page "Join us on our journey to the decentralized internet. Watch the video below to learn more about our mission and products." should become "Join us on our journey. Watch the video below and scroll down to learn how you can participate."
- Also on the action page, need to update the text "we’re excited to announce our next steps on December 12, 2024."

That's it for me for now. Thanks!

**Comment by Mik-TF** [comment]
Also:

A system built to scale to a planetary level, compatible with AI, Cloud, Web2, and Web3. Capable to provide 100% uptime, and enables any machine and human to communicate over the shortest path.

Should not use s for enables.

Capable to provide 100% uptime, it enables any...

**Comment by ehab-hassan** [comment]
done
https://dev.threefold.io/

@samtaggart @Mik-TF can you check before updating production

**Comment by samtaggart** [comment]
Hello @ehab-hassan yes we should change that. I know you are off, though. @sasha-astiadi or @samaradel can you help?

**Comment by samtaggart** [comment]
And just a small change on the action page ...

"For over a decade, ThreeFold has been dedicated to realizing this vision. Now is time for our next chapter."

**Comment by sasha-astiadi** [comment]
- [ ] Menu should be Take Action, not Take Actions (yes you can take multiple actions but it sounds weird)

- [ ] Any button that says "Pre-register now" (appears on multiple pages) should instead be something like "Sign Up Today" or "Take the Next Step" ... or something similar (maybe ask around for the right wording). Since the form allows people to do different things – register interest, pre-order, or order.

- [ ] On the action page "Join us on our journey to the decentralized internet. Watch the video below to learn more about our mission and products." should become "Join us on our journey. Watch the video below and scroll down to learn how you can participate."

- [ ] Also on the action page, need to update the text "we’re excited to announce our next steps on December 12, 2024."

- [ ] "For over a decade, ThreeFold has been dedicated to realizing this vision. Now is time for our next chapter.

- [ ] also at the dashboard status, the Capacity changed to GB should we change it also at io?

**Comment by sasha-astiadi** [comment]
@ehab-hassan for the gb on grid_stats  ill let you handle it ehab bc i dont wanna mess it up, the rest is done thanks again.

**Comment by ehab-hassan** [comment]
updated at staging https://dev.threefold.io/
![image](https://github.com/user-attachments/assets/109c354d-4037-4dc6-8817-c95f498c1aa6)
